/*
 * Copyright (c) 2020 Spica Systems Inc. All Rights Reserved.
 */
package main

import (
	"fmt"                            // REST-API Package
	_ "image_registry/rest_svr/docs" // docs is generated by Swag CLI, you have to import it.
	"net/http"

	"github.com/gorilla/mux"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

var router = mux.NewRouter()

//This is a test function
func testFunc(w http.ResponseWriter, r *http.Request) {
	//This will be printed on server log
	fmt.Println("Hello inside testFunc")
}
func uri_init() {
	router.HandleFunc("/", testFunc).Methods("GET")
}

func main() {

	// Register all URIs
	uri_init()
	fmt.Println("Server started...")
	//err := http.ListenAndServeTLS(":5002", "cert.pem", "key.pem", router)
	err := http.ListenAndServeTLS(":5002", "example.crt", "example.key", router)
	//err := http.ListenAndServeTLS(":5002", "/spica/certs/smcmp_registry.crt", "/spica/certs/smcmp_registry.key", router)
	if err != nil {
		fmt.Println("Error...", err)
	}
	//log.Fatal(http.ListenAndServe(":5002", router))
}

//=============================================================
//Create certificate and key
// openssl req -newkey rsa:4096 \
//             -x509 \
//             -sha256 \
//             -days 3650 \
//             -nodes \
//             -out example.crt \
//             -keyout example.key \
//             -subj "/C=SI/ST=Ljubljana/L=Ljubljana/O=Security/OU=IT Department/CN=localhost"

//=============================================================
//Create certificate and key
//openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem
